name: Run Discord Bot

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh chính (main)
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào nhánh chính (main)

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Lấy mã nguồn từ repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install  # Cài đặt các phụ thuộc của dự án

      - name: Deploy slash commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: node deploy-commands.js  # Đăng ký các slash commands

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node bot.js  # Chạy bot Discord
